---
title: "Data Exploration & Visualisation"
author: "adamlaycock"
date: "2024-09-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Load Packages
```{r load packages}
library(nycflights13)
library(tidyselect)
library(dplyr)
```
# Data Exploration & Manipulation
## Exploring the Dataset
### View Data
```{r explore the dataset}
head(flights)
```
### Check Dimensions
```{r check dimensions}
dim(flights)
```
## Filtering Flights
### Average Carrier Delays
```{r summarise}
group_by(flights, carrier) %>%
  summarise(mean(arr_delay, na.rm = TRUE))
```
### Arrival Delays
```{r delay filtering}
filter(flights, arr_delay > 120) %>%
  arrange(desc(arr_delay))
```
### JFK Departure
```{r origin filter}
filter(flights, origin == 'JFK')
```
## Column Selection
### Shrink the dataset
```{r dataset shrink}
sml_flights <- select(flights, year:day, ends_with('delay'), carrier, origin, dest)
head(sml_flights)
```
## Create New Columns
### Total delay creation
```{r}
mutate(sml_flights, total_delay = arr_delay + dep_delay) %>%
head()
```
## Summarise Data
```{r}
group_by(flights, origin) %>%
  summarise(mean(arr_delay, na.rm = TRUE))
```





